### ISSUE TITLE
Several Settings in orgPreferenceSettings Cause 'ProblemDeployingSettings: Failed to deploy settings to scratch org' Error

### ISSUE THREAD

**Issue by jty-reman** [forcedotcom/schemas#2]
I have been experimenting with changing from orgPreferences to settings in my Scratch definition file and I have discovered that the presence of any of these options causes an error when creating the scratch org:

"documentContentSearchEnabled": true,
"knowledgeEnabled": true,
"nameSuffixEnabled": true,
"middleNameEnabled": true
"liveAgentEnabled": true,
"chatterProfileEnabled": true

The other settings I am using that all do work fine are:
      "chatterEnabled": true,
      "enhancedEmailEnabled": true,
      "networksEnabled": true,
      "pathAssistantsEnabled": true,
      "notesReservedPref01": true,

But, adding any of the first list (one at a time or in combination) causes the error with JSON output:

```
"ProblemDeployingSettings: Failed to deploy settings to scratch org.\n    at ALMError (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\lib\\core\\almError.js:44:19)\n    at settings.createDep
loyDir.then.catch.err (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\lib\\core\\scratchOrgApi.js:772:37)\nOuter stack:\n    at Function.wrap (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97
a7df8\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at OrgCreateCommand.catch (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:216:46)"
```

**Comment by mshanemc** [comment]
orgPreferenceSettings is deprecated, closing.
