### ISSUE TITLE
sfdx-cli shouldn't crash because there's a `$schema` property in `sfdx-project.json`

### ISSUE THREAD

**Issue by Goobles** [forcedotcom/schemas#64]
### Summary

The property "$schema" is not allowed in sfdx-project.json (as described in https://forcedotcom.github.io/schemas/)

I don't think I need to explain why this is problematic. This means you have to add the $schema property every time you edit the file, then remove it afterwards when using the cli because sfdx cli throws this error:
```
Error: error during "initializing package version creation "Core"@0.105.0.NEXT"
reason: InvalidJsonCasing 
message: All JSON input must have heads down camelcase keys. E.g., `{ sfdcLoginUrl: "https://login.salesforce.com" }`
Found "$schema" at /sfdx-project.json
stack: InvalidJsonCasing: All JSON input must have heads down camelcase keys. E.g., `{ sfdcLoginUrl: "https://login.salesforce.com" }`
Found "$schema" at ./sfdx-project.json
    at Messages.createError (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@salesforce/core/lib/messages.js:446:16)
    at SfProjectJson.validateKeys (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@salesforce/core/lib/sfProject.js:314:32)
    at SfProjectJson.readSync (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@salesforce/core/lib/sfProject.js:66:14)
    at PackageVersionCreateCommand._execute (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/salesforce-alm/dist/lib/package/packageVersionCreateCommand.js:625:23)
    at PackageVersionCreateCommand.execute (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/salesforce-alm/dist/lib/package/packageVersionCreateCommand.js:563:21)
    at PackageVersionCreateCommand.execLegacyCommand (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:43)
    at PackageVersionCreateCommand.execPackagingLegacyCommand (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/salesforce-alm/dist/PackagingToolbeltCommand.js:37:28)
    at PackageVersionCreateCommand.run (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/salesforce-alm/dist/commands/force/package/version/create.js:23:21)
    at async PackageVersionCreateCommand._run (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)
    at async Config.runCommand (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async run (/Users/gobiusdolhain/.local/share/sfdx/client/7.177.1-617a284/node_modules/@oclif/core/lib/main.js:74:5)
    at /Users/gobiusdolhain/.nvm/versions/node/v16.18.0/lib/node_modules/@sparklink/cli/dist/cmds/2gp/utils.js:80:15
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gobiusdolhain/.nvm/versions/node/v16.18.0/lib/node_modules/@sparklink/cli/dist/cmds/2gp/utils.js:5:58)

```

### Expected result

sfdx-cli shouldn't crash because there's a `$schema` property in `sfdx-project.json`

### Actual result

sfdx-cli commands crashes because there's a `$schema` property in `sfdx-project.json`

**Comment by mshanemc** [comment]
been fixed for a while with the code here
https://github.com/forcedotcom/sfdx-core/blob/69ce01d1b00865362ccaa2cd8ce680ce964f2f82/src/util/findUppercaseKeys.ts#L15-L16

2 different teams between that repo and this so never closed until now.
